### ISSUE TITLE
Suggest moving the gateway mex entry point into +libmexclass/

### ISSUE THREAD

**Issue by jhughes-mw** [mathworks/libmexclass#22] opened 2023-01-19 18:07 UTC
gateway feels like a pretty generic name. Namespaceing it probably makes sense

**Comment by sreeharihegden** [comment] 2023-02-27 18:33
Duplicate of #34 
Closing this, as I just noticed #34 is for the same issue and I am working on it now.

**Closed as not planned** 2023-02-27 18:33 UTC
Labels: duplicate
