### ISSUE TITLE
Install with Visual Studio build doesn't install the "Release" folder

### ISSUE THREAD

**Issue by jhughes-mw** [mathworks/libmexclass#10] opened 2023-01-11 21:02 UTC
See this snippit from the install:

install/libmexclass/Release/gateway.exp
install/libmexclass/Release/gateway.lib
install/libmexclass/Release/gateway.mexw64
install/libmexclass/Release/mexclass.dll
install/libmexclass/Release/mexclass.exp
install/libmexclass/Release/mexclass.lib

The extra "Release" folder isn't accounted for.

**Comment by sreeharihegden** [comment] 2023-03-09 16:01
This gets resolved by #41 as we package the necessary binaries along with the MATLAB source into `+libmexclass/+proxy` on all platforms.

Marking as a duplicate of #28.

**Closed as not planned** 2023-03-09 16:02 UTC
Labels: bug, duplicate
